"""Rebrands browser/omni.ja: pattern-replaces "LibreWolf" -> "Wisp" in brand
strings, and swaps the in-app wolf-logo PNGs for Wisp's icon.

Text scope (confirmed by auditing every case-sensitive "LibreWolf" occurrence
in the 152.0-1 omni.ja — see wisp-v1-build-plan.md Task 7):
  - chrome/<locale>/locale/branding/brand.dtd       (104 files)
  - chrome/<locale>/locale/branding/brand.properties (104 files)
  - localization/<locale>/branding/brand.ftl         (104 files)
  - chrome/<locale>/locale/browser/appstrings.properties (104 files, network
    error page text, e.g. "LibreWolf can't find the server at %S.")
  - chrome/browser/content/browser/aboutDialog.xhtml (1 file, the About-box
    wordmark label only)
417 files total. Deliberately excludes every lowercase "librewolf" occurrence
elsewhere in omni.ja (pref names, Fluent l10n-ids, the LibreWolf-specific
about:preferences pane's own JS/CSS/SVG, devtools flags) — those are internal
code identifiers, not display text, and renaming them would require rewriting
cross-references across many files for no user-visible benefit, with real risk
of breaking that pane's functionality.

Icon scope: chrome/browser/content/branding/icon{16,32,48,64,128}.png — the
wolf-head logo shown on about:support and the Help menu. This is separate from
the blank about-logo.svg/png stubs (LibreWolf ships those empty) and separate
from the .exe icon (swapped by rcedit, not this script). Replaced with
rebrand/icon/omni-icons/icon<N>.png, generated by export_ico.py.

Usage: rebrand_strings.py <path-to-omni.ja> [--dry-run]
Rewrites the file in place (via a temp file + atomic replace) unless --dry-run.
Prints a per-category match-count report so the result is auditable without a
manual diff.
"""
import argparse
import fnmatch
import re
import sys
import zipfile
from pathlib import Path

OLD = "LibreWolf"
NEW = "Wisp"

TEXT_PATTERNS = [
    "chrome/*/locale/branding/brand.dtd",
    "chrome/*/locale/branding/brand.properties",
    "localization/*/branding/brand.ftl",
    "chrome/*/locale/browser/appstrings.properties",
    "chrome/browser/content/browser/aboutDialog.xhtml",
]

# chrome/browser/content/branding/icon<N>.png: LibreWolf's in-app wolf-logo
# (about:support, Help menu, etc) — a separate asset from the .exe icon that
# rcedit swaps. Replaced with Wisp's matching-size renders from export_ico.py.
ICON_DIR = Path(__file__).parent / "icon" / "omni-icons"
ICON_REPLACEMENTS = {
    f"chrome/browser/content/branding/icon{size}.png": ICON_DIR / f"icon{size}.png"
    for size in (16, 32, 48, 64, 128)
}


def matches_scope(name):
    return any(fnmatch.fnmatch(name, p) for p in TEXT_PATTERNS)


def rebrand_zip(src_path, dst_path):
    report = {
        "files_patched": 0,
        "files_in_scope_unchanged": 0,
        "substitutions": 0,
        "icons_replaced": 0,
    }
    unexpected = []

    with zipfile.ZipFile(src_path, "r") as zin:
        names_in_scope = [n for n in zin.namelist() if matches_scope(n)]
        icon_names_found = [n for n in zin.namelist() if n in ICON_REPLACEMENTS]
        with zipfile.ZipFile(dst_path, "w") as zout:
            for item in zin.infolist():
                data = zin.read(item.filename)
                if matches_scope(item.filename):
                    text = data.decode("utf-8")
                    new_text, count = re.subn(re.escape(OLD), NEW, text)
                    if count:
                        report["files_patched"] += 1
                        report["substitutions"] += count
                    else:
                        report["files_in_scope_unchanged"] += 1
                    data = new_text.encode("utf-8")
                elif item.filename in ICON_REPLACEMENTS:
                    data = ICON_REPLACEMENTS[item.filename].read_bytes()
                    report["icons_replaced"] += 1
                zout.writestr(item, data)

    expected_file_count = (
        104  # brand.dtd
        + 104  # brand.properties
        + 104  # brand.ftl
        + 104  # appstrings.properties
        + 1  # aboutDialog.xhtml
    )
    if len(names_in_scope) != expected_file_count:
        unexpected.append(
            f"expected {expected_file_count} in-scope text files, found {len(names_in_scope)}"
        )
    if len(icon_names_found) != len(ICON_REPLACEMENTS):
        unexpected.append(
            f"expected {len(ICON_REPLACEMENTS)} branding icons, found {len(icon_names_found)}"
        )

    return report, unexpected


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("omni_ja", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    tmp_path = args.omni_ja.with_suffix(".ja.tmp")
    report, unexpected = rebrand_zip(args.omni_ja, tmp_path)

    print(f"files patched:            {report['files_patched']}")
    print(f"in-scope but no match:    {report['files_in_scope_unchanged']}")
    print(f"total substitutions:      {report['substitutions']}")
    print(f"branding icons replaced:  {report['icons_replaced']}")
    if unexpected:
        print("UNEXPECTED:")
        for u in unexpected:
            print(f"  - {u}")
    else:
        print("0 unexpected matches")

    if args.dry_run:
        tmp_path.unlink()
        print("(dry run, omni.ja left unchanged)")
    else:
        tmp_path.replace(args.omni_ja)
        print(f"wrote {args.omni_ja}")

    if unexpected:
        sys.exit(1)


if __name__ == "__main__":
    main()
