"""Rebrands browser/omni.ja: pattern-replaces "LibreWolf" -> "Wisp" in brand
strings, swaps the in-app wolf-logo PNGs, and swaps the inline base64 wolf-logo
SVG embedded directly in aboutDialog.css.

Text scope (confirmed by auditing every case-sensitive "LibreWolf" occurrence
in the 152.0-1 omni.ja; locale count bumped to 105 as of 154.0.1-3, which
added "ku" (Kurdish) — spot-checked to carry the same 7 files as every other
locale, no scope changes needed beyond the count):
  - chrome/<locale>/locale/branding/brand.dtd            (105 files)
  - chrome/<locale>/locale/branding/brand.properties     (105 files)
  - localization/<locale>/branding/brand.ftl             (105 files)
  - chrome/<locale>/locale/browser/appstrings.properties (105 files, network
    error page text, e.g. "LibreWolf can't find the server at %S.")
  - chrome/browser/content/browser/aboutDialog.xhtml     (1 file, the
    About-box wordmark label)
  - localization/<locale>/browser/aboutDialog.ftl        (105 files checked;
    only ~29 actually contain a literal match — the rest phrase their own
    translation differently. en-US's copy matters regardless, since Fluent
    falls back to it for any locale whose own file doesn't override a
    message.) The "about-librewolf" message itself.
  - localization/<locale>/browser/preferences/preferences.ftl (105 files
    checked, ~31 contain matches) — the LibreWolf settings-pane *title and
    descriptive text values* (e.g. "librewolf-header = LibreWolf
    Preferences"). NOT the same thing as the pane's lowercase message IDs
    (pane-librewolf-title2, librewolf-header) or its JS/CSS/SVG, which stay
    untouched — see exclusions below.
  - localization/<locale>/browser/browser.ftl (105 files checked, 10 contain
    a match) — some locales' own translators prefixed the
    "identity-allow-site-data" string with "LibreWolf: ", which en-US's
    source string doesn't even do.
736 files checked in total (most are no-ops; only the locales whose own
translation contains a literal match get patched). Every pattern's actual
in-scope file count is verified at runtime against an expected count (see
PATTERN_EXPECTED_COUNTS) rather than trusting a single hand-summed total —
a hand-summed "417" total is exactly what let the follow-up gap (aboutDialog
text/icon, the three patterns above) go unnoticed the first time.

Deliberately excludes every lowercase "librewolf" occurrence elsewhere in
omni.ja (pref names, Fluent l10n-ids/message keys, the LibreWolf-specific
about:preferences pane's own JS/CSS/SVG files, devtools flags) — confirmed via
case-sensitive (not case-insensitive) re-grep that none of those files contain
an actual exact-case "LibreWolf" display string, only lowercase identifiers.
Renaming those would require rewriting cross-references across many files for
no user-visible benefit, with real risk of breaking that pane's functionality.

Icon scope:
  - chrome/browser/content/branding/icon{16,32,48,64,128}.png — the wolf-head
    logo shown on about:support and the Help menu. Replaced with
    rebrand/icon/omni-icons/icon<N>.png (generated by export_ico.py).
  - chrome/browser/content/browser/aboutDialog.css — the About window's logo
    is a *separate* copy of the wolf, inline as a base64 SVG data URI inside
    this one CSS file (not a reference to icon128.png or any other shared
    asset). Replaced by re-encoding rebrand/icon/wisp.svg as base64 and
    substituting it into the same `url("data:image/svg+xml;base64,...")`
    rule. Confirmed via fingerprint search that this exact data URI is not
    duplicated anywhere else in omni.ja.
  - chrome/browser/content/branding/about-logo(.png|@2x.png|-private.png|
    -private@2x.png) and firefox-wordmark.svg — the New Tab / Private
    Browsing page's "empty state" logo+wordmark, added upstream since
    152.0-1 (found 2026-08-29: with FirefoxHome content policy-disabled,
    this becomes the dominant visible thing on those pages instead of being
    covered up by Top Sites/Highlights). The 4 PNGs are two byte-identical
    pairs upstream (confirmed via sha256) — replaced with rebrand/icon/
    about-logo/about-logo-{192,384}.png (export_ico.py, same wisp glyph as
    the icon<N>.png set, just at the larger sizes this component needs).
    firefox-wordmark.svg is upstream's own vector-path "librewolf" logotype
    (drawn as bezier curves, not text — a case-sensitive string search won't
    find it) — replaced with rebrand/icon/wordmark.svg, an SVG <text> reading
    "Wisp" at the same viewBox so the CSS that sizes/centers it needs no
    changes, keeping the original's fill:context-fill theming mechanism.
    chrome/browser/content/branding/about-logo.svg (a different, unrelated
    asset used on the welcome screen, profile selector, and "more from
    Mozilla" pane) is deliberately left untouched — upstream itself ships it
    as an empty placeholder with no content, so there's no LibreWolf branding
    there to begin with.

Usage: rebrand_strings.py <path-to-omni.ja> [--dry-run]
Rewrites the file in place (via a temp file + atomic replace) unless --dry-run.
Prints a per-category match-count report so the result is auditable without a
manual diff.
"""
import argparse
import base64
import fnmatch
import re
import sys
import zipfile
from pathlib import Path

OLD = "LibreWolf"
NEW = "Wisp"

# pattern -> expected number of zip entries matching it, checked at runtime.
PATTERN_EXPECTED_COUNTS = {
    "chrome/*/locale/branding/brand.dtd": 105,
    "chrome/*/locale/branding/brand.properties": 105,
    "localization/*/branding/brand.ftl": 105,
    "chrome/*/locale/browser/appstrings.properties": 105,
    "chrome/browser/content/browser/aboutDialog.xhtml": 1,
    "localization/*/browser/aboutDialog.ftl": 105,
    "localization/*/browser/preferences/preferences.ftl": 105,
    "localization/*/browser/browser.ftl": 105,
}
TEXT_PATTERNS = list(PATTERN_EXPECTED_COUNTS)

ICON_DIR = Path(__file__).parent / "icon" / "omni-icons"
ICON_REPLACEMENTS = {
    f"chrome/browser/content/branding/icon{size}.png": ICON_DIR / f"icon{size}.png"
    for size in (16, 32, 48, 64, 128)
}

# The New Tab / Private Browsing "empty state" logo+wordmark (added upstream
# since 152.0-1 — visible once FirefoxHome content is policy-disabled, since
# it's no longer covered up by Top Sites/Highlights). about-logo(-private)
# and its @2x are byte-identical pairs upstream (confirmed via sha256), so
# both names get the same rendered PNG.
ABOUT_LOGO_DIR = Path(__file__).parent / "icon" / "about-logo"
for _name in ("about-logo.png", "about-logo-private.png"):
    ICON_REPLACEMENTS[f"chrome/browser/content/branding/{_name}"] = ABOUT_LOGO_DIR / "about-logo-192.png"
for _name in ("about-logo@2x.png", "about-logo-private@2x.png"):
    ICON_REPLACEMENTS[f"chrome/browser/content/branding/{_name}"] = ABOUT_LOGO_DIR / "about-logo-384.png"

ICON_REPLACEMENTS["chrome/browser/content/branding/firefox-wordmark.svg"] = (
    Path(__file__).parent / "icon" / "wordmark.svg"
)

# chrome/browser/content/branding/about-logo.svg is deliberately left untouched:
# upstream itself ships it as an empty placeholder (<svg .../> with no content)
# across several surfaces (welcome screen, profile selector, "more from
# Mozilla" pane) — it already shows no LibreWolf branding, so there's nothing
# to rebrand there.

ABOUT_DIALOG_CSS = "chrome/browser/content/browser/aboutDialog.css"
WISP_SVG = Path(__file__).parent / "icon" / "wisp.svg"
DATA_URI_RE = re.compile(r'(url\("data:image/svg\+xml;base64,)([A-Za-z0-9+/=]+)("\))')

NEWTAB_CSS = "chrome/browser/builtin-addons/newtab/data/css/activity-stream.css"
SOCIAL_PREVIEW = Path(__file__).parent / "icon" / "social-preview.png"

# aboutDialog.xhtml's website link is a literal hardcoded URL (lowercase
# "librewolf.net", so the case-sensitive LibreWolf->Wisp text pass correctly
# leaves it alone) used as both the href and its own visible link text — not
# driven by any of the app.support.baseURL-style prefs already repointed in
# librewolf.cfg.append, since it's baked directly into this one file's markup.
ABOUT_DIALOG_XHTML = "chrome/browser/content/browser/aboutDialog.xhtml"
OLD_WEBSITE_URL = "https://librewolf.net/"
NEW_WEBSITE_URL = "https://github.com/ukkit/wisp-browser"


def matches_scope(name):
    return any(fnmatch.fnmatch(name, p) for p in TEXT_PATTERNS)


def patch_about_dialog_css(data):
    svg_text = re.sub(r"\s+", " ", WISP_SVG.read_text("utf-8")).strip()
    svg_text = re.sub(r"<!--.*?-->", "", svg_text, flags=re.DOTALL)
    b64 = base64.b64encode(svg_text.encode("utf-8")).decode("ascii")
    text = data.decode("utf-8")
    new_text, count = DATA_URI_RE.subn(rf"\g<1>{b64}\g<3>", text)
    return new_text.encode("utf-8"), count


def inject_newtab_bg_css(data):
    png_b64 = base64.b64encode(SOCIAL_PREVIEW.read_bytes()).decode()
    suffix = (
        "\n/* Wisp: branded new-tab background */\n"
        f"html{{background:#2a2d6e url('data:image/png;base64,{png_b64}')"
        "center/cover no-repeat fixed!important}}\n"
        "body,.outer-wrapper{background:transparent!important}\n"
    )
    return data + suffix.encode("utf-8")


def rebrand_zip(src_path, dst_path):
    report = {
        "files_patched": 0,
        "files_in_scope_unchanged": 0,
        "substitutions": 0,
        "icons_replaced": 0,
        "css_icon_replaced": 0,
        "website_link_replaced": 0,
        "newtab_bg_injected": 0,
    }
    unexpected = []

    with zipfile.ZipFile(src_path, "r") as zin:
        all_names = zin.namelist()
        names_in_scope = [n for n in all_names if matches_scope(n)]
        icon_names_found = [n for n in all_names if n in ICON_REPLACEMENTS]

        with zipfile.ZipFile(dst_path, "w") as zout:
            for item in zin.infolist():
                data = zin.read(item.filename)
                if matches_scope(item.filename):
                    text = data.decode("utf-8")
                    new_text, count = re.subn(re.escape(OLD), NEW, text)
                    if count:
                        report["files_patched"] += 1
                        report["substitutions"] += count
                    else:
                        report["files_in_scope_unchanged"] += 1
                    if item.filename == ABOUT_DIALOG_XHTML:
                        # both the href and the link's own visible text are the
                        # same literal URL string, so 2 matches is correct here
                        new_text, url_count = re.subn(
                            re.escape(OLD_WEBSITE_URL), NEW_WEBSITE_URL, new_text
                        )
                        if url_count != 2:
                            unexpected.append(
                                f"{ABOUT_DIALOG_XHTML}: expected 2 website-link "
                                f"replacements (href + visible text), made {url_count}"
                            )
                        report["website_link_replaced"] += url_count
                    data = new_text.encode("utf-8")
                elif item.filename in ICON_REPLACEMENTS:
                    data = ICON_REPLACEMENTS[item.filename].read_bytes()
                    report["icons_replaced"] += 1
                elif item.filename == ABOUT_DIALOG_CSS:
                    data, count = patch_about_dialog_css(data)
                    if count != 1:
                        unexpected.append(
                            f"{ABOUT_DIALOG_CSS}: expected 1 data-URI replacement, made {count}"
                        )
                    report["css_icon_replaced"] += count
                elif item.filename == NEWTAB_CSS:
                    data = inject_newtab_bg_css(data)
                    report["newtab_bg_injected"] += 1
                zout.writestr(item, data)

    for pattern, expected in PATTERN_EXPECTED_COUNTS.items():
        actual = sum(1 for n in names_in_scope if fnmatch.fnmatch(n, pattern))
        if actual != expected:
            unexpected.append(f"{pattern}: expected {expected} files, found {actual}")
    if len(icon_names_found) != len(ICON_REPLACEMENTS):
        unexpected.append(
            f"expected {len(ICON_REPLACEMENTS)} branding icons, found {len(icon_names_found)}"
        )
    if ABOUT_DIALOG_CSS not in all_names:
        unexpected.append(f"{ABOUT_DIALOG_CSS} not found in archive")
    if report["newtab_bg_injected"] != 1:
        unexpected.append(f"{NEWTAB_CSS}: expected 1 injection, got {report['newtab_bg_injected']}")

    return report, unexpected


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("omni_ja", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    tmp_path = args.omni_ja.with_suffix(".ja.tmp")
    report, unexpected = rebrand_zip(args.omni_ja, tmp_path)

    print(f"files patched:            {report['files_patched']}")
    print(f"in-scope but no match:    {report['files_in_scope_unchanged']}")
    print(f"total substitutions:      {report['substitutions']}")
    print(f"branding icons replaced:  {report['icons_replaced']}")
    print(f"aboutDialog.css icon:     {report['css_icon_replaced']} replacement")
    print(f"aboutDialog website link: {report['website_link_replaced']} replacements")
    if unexpected:
        print("UNEXPECTED:")
        for u in unexpected:
            print(f"  - {u}")
    else:
        print("0 unexpected matches")

    if args.dry_run:
        tmp_path.unlink()
        print("(dry run, omni.ja left unchanged)")
    else:
        tmp_path.replace(args.omni_ja)
        print(f"wrote {args.omni_ja}")

    if unexpected:
        sys.exit(1)


if __name__ == "__main__":
    main()
